# Generated by Django 5.0.3 on 2024-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0003_holding_hd_to_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdinginstance',
            name='hi_days',
            field=models.IntegerField(default=0, help_text='Instance days', verbose_name='Number Of Days'),
        ),
    ]
