# Generated by Django 5.0.3 on 2024-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0004_holdinginstance_hi_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdinginstance',
            name='hi_status',
            field=models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status', max_length=1, verbose_name='Status'),
        ),
    ]
