# Generated by Django 5.0.3 on 2024-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0005_alter_holdinginstance_hi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='ot_status',
            field=models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1', help_text='Status of the notes', max_length=1, verbose_name='Status'),
        ),
    ]
