# Generated by Django 5.0.3 on 2024-04-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0009_rename_so_sn_code_customer_cs_sn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cs_type',
            field=models.CharField(choices=[('C', 'Cash'), ('A', 'Account')], default='1', help_text='Type of the customer', max_length=200, verbose_name='Customer Type'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='si_pt_code',
            field=models.ForeignKey(help_text='Package Type', on_delete=django.db.models.deletion.CASCADE, related_name='packagetype', to='chicks.packtype', verbose_name='Package Type'),
        ),
    ]
