# Generated by Django 5.0.3 on 2024-04-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0010_alter_customer_cs_type_alter_stockitem_si_pt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='cu_base',
            field=models.CharField(choices=[('Y', 'Home Currency'), ('1', 'Currency 1'), ('2', 'Currency 1')], default='N', help_text='Indicates whether the currency is the base currency', max_length=1, verbose_name='Base Currency ?'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_base_amnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Base Amnt', max_digits=15, null=True, verbose_name='Base Amnt'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_ord_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ordered Quantity', max_digits=15, null=True, verbose_name='O Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Exch. Rate', max_digits=15, null=True, verbose_name='Exch. Rate'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_rec_qty',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recieved Quantity', max_digits=15, null=True, verbose_name='R Quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_trans_amnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Trans. Amnt', max_digits=15, null=True, verbose_name='Trans. Amnt'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_ucost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Avg Cost', max_digits=15, null=True, verbose_name='Avg Cost'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_uprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Unit Price', max_digits=15, null=True, verbose_name='Unit Price'),
        ),
    ]
