# Generated by Django 5.0.3 on 2024-04-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0013_orderitem_oi_disc_amnt_orderitem_oi_tax_amnt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='io_cs_num',
            new_name='oi_cs_num',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='sl_sn_code',
            new_name='oi_sn_code',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='io_so_ord_date',
            new_name='oi_so_ord_date',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='io_so_p_s',
            new_name='oi_so_p_s',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='io_so_type',
            new_name='oi_so_type',
        ),
        migrations.RenameField(
            model_name='storeorder',
            old_name='sl_sn_code',
            new_name='so_sn_code',
        ),
    ]
