# Generated by Django 5.0.3 on 2024-05-02 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0014_rename_io_cs_num_orderitem_oi_cs_num_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packtype',
            options={'ordering': ['pt_code'], 'verbose_name': 'Packaging Type'},
        ),
        migrations.AlterModelOptions(
            name='storeorder',
            options={'ordering': ['so_type'], 'verbose_name': 'Store Order'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_cs_num',
            field=models.ForeignKey(blank=True, help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='chicks.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oi_so_num',
            field=models.ForeignKey(blank=True, help_text='Store Order', null=True, on_delete=django.db.models.deletion.CASCADE, to='chicks.storeorder', verbose_name='Store Order'),
        ),
    ]
