# Generated by Django 5.0.3 on 2024-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0017_orderitem_oi_disc_orderitem_oi_tax_stockitem_si_disc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='so_p_s',
            field=models.CharField(choices=[('P', 'Purchase Order'), ('S', 'Sales Order')], default='C', help_text='Type of the Order', max_length=1, verbose_name='Purchase/Sales'),
        ),
    ]
