# Generated by Django 5.0.3 on 2024-05-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0018_orderitem_so_p_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='so_p_s',
            new_name='oi_so_p_s',
        ),
    ]
