# Generated by Django 5.0.3 on 2024-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0019_rename_so_p_s_orderitem_oi_so_p_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='oi_so_p_s',
            field=models.CharField(choices=[('P', 'Purchase Order'), ('S', 'Sales Order')], default='S', help_text='Type of the Order', max_length=1, verbose_name='Purchase/Sales'),
        ),
    ]
